//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temagiydirme2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuvenlikDbEntities : DbContext
    {
        public GuvenlikDbEntities()
            : base("name=GuvenlikDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GKatagori> GKatagoris { get; set; }
        public virtual DbSet<GMusteri> GMusteris { get; set; }
        public virtual DbSet<GPersonel> GPersonels { get; set; }
        public virtual DbSet<GSipari> GSiparis { get; set; }
    }
}
