//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temagiydirme2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPersonel
    {
        public int PersonelId { get; set; }
        public string PerAdSoyad { get; set; }
        public string PerMail { get; set; }
        public string PerTel { get; set; }
        public string PerAdres { get; set; }
        public string KatagoriId { get; set; }
    }
}
